---

- hosts: vse
  gather_facts: false
  tasks:
  - name: Check availability
    ping:

- hosts: frontend
  gather_facts: false
  tasks:
  - name: Deploy site content
    copy: src=/home/gri/docker_ansible/index.html dest=/usr/share/nginx/www mode=06444

- hosts: backend
  tasks:
  - name: Check is service installed
    apt:
      name: sqlite
      state: present

- hosts: database
  tasks:
  - name: Add pip
    apt:
      name: python-pip
      state: present
  - name: Add PyMySQL module
    pip:
      name: pymysql
    


...
