---

- hosts: grilab.io
  gather_facts: no
  connection: local
  tasks:
    - name: Start frontend container
      docker_container:
        name: dyno_Frontend
        image: nginx
        user: root
        volumes:
         - /home/gri/docker_ansible/scripts:/tmp/ssh
        command: /bin/bash /tmp/ssh/ssh_provision.sh 

    - name: Start backend container
      docker_container:
        name: dyno_Backend
        image: nginx
        user: root
        volumes:
         - /home/gri/docker_ansible/scripts:/tmp/ssh
        command: /bin/bash /tmp/ssh/ssh_provision.sh

    - name: Start database container
      docker_container:
        name: dyno_Database
        image: mariadb
        user: root
        volumes:
         - /home/gri/docker_ansible/scripts:/tmp/ssh
        command: /bin/bash /tmp/ssh/ssh_provision.sh

    - name: Make dynamic inventory
      command: /home/gri/docker_ansible/scripts/ip_gather.sh
...
